[package]
name = "tcshare-ui"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
better-panic = "0.3.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
derive_setters = "0.1.6"
dialoguer = "0.11.0"
human-panic = "2.0.1"
libc = "0.2.158"
lipsum = "0.9.1"
ratatui = "0.28.1"
strip-ansi-escapes = "0.2.0"
tui-big-text = "0.6.0"
tui_confirm_dialog = "0.2.3"
