[package]
name = "tcshare-ui"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
better-panic = "0.3.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
derive_setters = "0.1.6"
dialoguer = "0.11.0"
dirs = "5.0.1"
human-panic = "2.0.1"
libc = "0.2.158"
lipsum = "0.9.1"
log = "0.4.22"
nanoid = "0.4.0"
rand = "0.8.5"
ratatui = "0.28.1"
serde = "1.0.210"
serde_json = "1.0.128"
strip-ansi-escapes = "0.2.0"
tui-big-text = "0.6.0"
tui-logger = "0.13.1"
tui-textarea = "0.6.1"
tui_confirm_dialog = "0.2.3"
whoami = "1.5.2"
